ihmeuw/ihme-ui

package.json
packages/beaut-test-utils/README.md
packages/beaut-test-utils/index.js
packages/beaut-test-utils/mocks/colors.js
packages/beaut-test-utils/mocks/mocks.js
packages/beaut-test-utils/package.json

small PR to get this module npm installable

Test utils

---

.eslintignore
package.json
src/ui/shape/test/area.test.js
src/ui/slider/test/slider-handle.test.js

fix `npm run lint` command to ensure test files are linted. 
fix lint errors in test files.

Fix lint issues

---

package.json
src/test-utils/data.js
src/test-utils/test/data.test.js

Made some changes to improve dataGenerator for axisChart.

change to dataGenerator

---

.eslintignore
package.json
src/ui/slider/demo/app.jsx
src/ui/slider/demo/html-pre-tag-loader.js
src/ui/slider/demo/index.html
src/ui/slider/demo/webpack.config.js
src/ui/slider/src/fill.jsx
src/ui/slider/src/handle.jsx
src/ui/slider/src/slider.jsx
src/ui/slider/src/style.css
src/ui/slider/src/ticks.jsx
src/ui/slider/src/track.jsx
src/ui/slider/src/util.js
src/ui/slider/test/.eslintrc.js
src/ui/slider/test/fill.test.js
src/ui/slider/test/ticks.test.js
src/ui/slider/test/track.test.js
src/ui/slider/test/util.test.js
src/utils/index.js
src/utils/props.js
src/utils/react.js
src/utils/test/props.test.js

Optimize child component rendering. @GabeMedrash, you were right about how components render, lets discuss.
Use `dX` to move handle instead of `pageX`, which makes handles track cursor at point of click instead of center.

Slider enhancements

---

package.json
src/ui/shape/demo/app.jsx
src/ui/shape/src/multi-scatter.jsx
src/ui/shape/src/scatter.jsx
src/ui/shape/src/symbol.jsx
src/ui/shape/test/scatter.test.js
src/ui/shape/test/symbol.test.js

Now you can select and focus on scatter symbols. See demo.

Symbol select

---

.eslintrc.js
package.json
src/ui/choropleth/src/choropleth.jsx
src/ui/choropleth/src/controls.css
src/ui/choropleth/src/controls.jsx
src/ui/choropleth/src/feature-layer.jsx
src/ui/choropleth/src/path.jsx
src/ui/choropleth/test/.eslintrc.js
src/ui/choropleth/test/choropleth.test.js
src/ui/choropleth/test/feature-layer.test.js
src/ui/choropleth/test/path.test.js
src/utils/props.js

Incremental enhancements to make disputed territories work possible

Choropleth enhancements

---

src/ui/tooltip/test/tooltip.test.js

remove .only from top-level of tooltip describe block

---

src/ui/shape/src/multi-line.jsx

To allow data to be transformed or filtered by key field.

add area and line iteratees to `MultiLine`

---

src/ui/shape/src/symbol.jsx
src/ui/shape/test/symbol.test.js

Add support for rotation modifier.

Symbols rotation

---

src/utils/numbers.js
src/utils/test/numbers.test.js

module to abstract simple math operations that may result in floating point imprecision errors

floating point math module

---

src/ui/slider/demo/app.jsx
src/ui/slider/src/handle.jsx
src/ui/slider/src/slider.jsx

to `onDrag`, `onDragEnd`, `onKey`, `onKeyEnd`, and `onTrackClick`

Rework Slider API to split out functionality for `onChange`

---

src/ui/axis/src/axis.jsx

Alphabetized the propTypes for Axis. Changed comments to reflect change in position.
Tests have 256 passing (2s), 2 pending.

issue 67 alphabetized the propTypes in axis

---

package.json
src/ui/axis/src/axis.jsx

Changed the Axis label propType from "any" to "string".

Issue 69- changed Axis label Proptype from any to string

---

src/utils/numbers.js
src/utils/test/numbers.test.js

Made some adjustments to make float object handle the case of 64.79 - 64.75. Added an extra buffer to `floatToIntMultiplier` and use a floor function to handle the case of 64.79 * 1000. Added tests.

Numbers fix

---

src/ui/select/src/select-option.jsx

use lodash includes instead of includes off array prototype

---

src/ui/expansion-container/demo/app.jsx
src/ui/expansion-container/src/Expandable.jsx

Mouse events are added to the expandable component so that when the mouse interacts with the button, we can provide callbacks.

Expandable hover

---

package.json
src/ui/index.js
src/ui/legend/README.md
src/ui/legend/_readme.template.md
src/ui/legend/index.js
src/ui/legend/src/legend-item.jsx
src/ui/legend/src/legend-title.jsx
src/ui/legend/src/legend.jsx
src/ui/legend/test/legend-item.test.js
src/ui/legend/test/legend.test.js

Legend: standardize className and style props

---

src/ui/choropleth/src/choropleth.jsx
src/ui/compositions/choropleth-legend/src/slider-handle.jsx
src/ui/expansion-container/src/ExpansionContainer.jsx

Unbind event handlers and free references on componentWillUnmount of various components.

Memory management

---

.travis.yml
package-lock.json
package.json

- Uninstall `canvas` and update Travis config.
- Install `canvas-prebuilt` to fix Travis npm build.

patch up Travis build one more time, again.

---

package.json

After merging Komal's PR to enable bolding an option label I'm incrementing/publishing the changes on npm.

Update version to 0.30.0

---

package-lock.json

Something seems to have been an issue with the last dependency patch; attempting once more.

Fix vulnerable dependency: hoek

---

src/ui/select/src/select.jsx

This is the tiniest of PRs to allow the select dropdown to be disabled with a prop.

Add a `disabled` prop to be able to disable the select component.

---

src/ui/compositions/map/demo/app.jsx
src/ui/compositions/map/src/map.jsx

Update IHME-UI map to allow for the new way that we handle disputed territories.

Update how disputed locations are matched in map.jsx

---

package-lock.json
src/ui/axis-chart/README.md
src/ui/axis-chart/src/axis-chart.jsx
src/ui/compositions/bar-chart/README.md
src/ui/compositions/bar-chart/src/bar-chart.jsx
src/utils/axis.js

Made some minor changes to allow for an axisStyle prop in the AxisChart component and also exposed this prop on the bar chart composition.
**_NOTE:_** I was trying to publish a release candidate to npm and accidentally made a minor release from this branch. Everything seems to be working fine and nothing should be affected since it's just the addition of new props.

Stp 616 bar chart tickmarks
