src/ui/axis-chart/demo/app.jsx, src/ui/axis-chart/index.js, src/ui/axis-chart/test/axis-chart.test.js, src/ui/axis/demo/app.jsx, src/ui/axis/index.js, src/ui/axis/test/axis.test.js, src/ui/button/demo/app.jsx, src/ui/button/index.js, src/ui/button/src/button.jsx, src/ui/button/test/button.test.js, src/ui/group/demo/app.jsx, src/ui/group/demo/html-pre-tag-loader.js, src/ui/group/demo/index.html, src/ui/group/demo/webpack.config.js, src/ui/group/index.js, src/ui/group/src/group.css, src/ui/group/src/group.jsx, src/ui/group/src/option.jsx, src/ui/group/test/group.test.js, src/ui/group/test/option.test.js, src/ui/html-label/index.js, src/ui/html-label/src/html-label.jsx, src/ui/html-label/test/html-label.test.js, src/ui/range-slider/src/index.js, src/ui/shape/demo-scatter-plot/app.jsx, src/ui/shape/demo-symbol/app.jsx, src/ui/shape/index.js, src/ui/spinner/index.js, src/utils/index.js
This branch cleans up `<Button>` and `<HtmlLabel>` a bit by attempting to standardize the props interface, and adds grouping functionality through `<Group>`.
`<Group>` will contain `<Option>` elements, which by default render `<Button>`s and inherit style from the `<Group>`.
=> Add Button Groups

src/ui/choropleth/demo/app.jsx, src/ui/choropleth/src/choropleth.jsx, src/ui/choropleth/src/feature-layer.jsx
to specify the key field on the geoJSON, if it isn't the default 'id'.
=> Add `geoJSONKeyField`

src/ui/legend/src/legend-item.css
Fixes faulty width constraint in parent element.
=> Set legend item svg to flex-basis auto.

.babelrc, .eslintignore, .eslintrc.js, README.md, package.json, src/ui/axis-chart/demo/app.jsx, src/ui/axis-chart/demo/html-pre-tag-loader.js, src/ui/axis-chart/demo/index.html, src/ui/axis-chart/demo/webpack.config.js, src/ui/axis-chart/src/axis-chart.jsx, src/ui/axis-chart/test/axis-chart.test.js, src/ui/axis/demo/app.jsx, src/ui/axis/demo/html-pre-tag-loader.js, src/ui/axis/demo/webpack.config.js, src/ui/axis/src/axis.jsx, src/ui/axis/src/utils.js, src/ui/axis/src/x-axis.jsx, src/ui/axis/src/y-axis.jsx, src/ui/axis/test/axis.test.js, src/ui/axis/test/utils.test.js, src/ui/shape/src/multi-line.jsx, src/ui/shape/src/multi-scatter.jsx, src/utils/index.js, src/utils/props.js, src/utils/scale.js, src/utils/symbol.js, src/utils/test/scale.test.js, src/utils/test/symbol.test.js, starter-app/app.jsx
Notes:
* label is added to `<Axis />` as a prop
* label is placed based on orientation, drawn against the inside edge of the padding
* for label, must supply padding to `<Axis />`
* dimensions prop flattened to width, height
* default orientation removed for `<Axis />`
* default scales are provided for `<[XY]?Axis />` and `<Multi(Line|Scatter) />` to avoid run time warnings
* unit test coverage has been improved
=> Axis label enhancements

src/ui/axis-chart/demo/app.jsx, src/ui/button/demo/app.jsx, src/ui/button/demo/html-pre-tag-loader.js, src/ui/button/demo/webpack.config.js, src/ui/button/src/button.jsx, src/ui/button/test/button.test.js, src/ui/choropleth-legend/demo/app.jsx, src/ui/choropleth/demo/app.jsx, src/ui/choropleth/src/controls.jsx, src/ui/group/demo/app.jsx, src/ui/group/demo/html-pre-tag-loader.js, src/ui/group/demo/webpack.config.js, src/ui/group/src/group.css, src/ui/group/src/group.jsx, src/ui/group/src/option.jsx, src/ui/group/test/.eslintrc.js, src/ui/group/test/group.test.js, src/ui/group/test/option.test.js, src/ui/legend/demo/app.jsx, src/ui/slider/demo/app.jsx
This resolves an issue with `Group` and `Option`s not showing correct styling because `Button` was stomping on them.
Cleaned up `className` handling.
Added new `className` and `style` props for `selected` and `disabled`.
Made `Group`, `Option`, and `Button` extend `PureComponent` for efficient rendering.
Tried to maintain backwards compatibility as much as possible.
@davschne: Please review this and make sure it suits your needs
=> Option button enhancements

src/ui/axis-chart/src/axis-chart.jsx, src/ui/axis-chart/test/axis-chart.test.js, src/ui/shape/src/area.jsx, src/ui/shape/src/line.jsx, src/ui/shape/src/multi-line.jsx, src/ui/shape/src/multi-scatter.jsx, src/ui/shape/src/scatter.jsx, src/ui/shape/src/symbol.jsx
These changes give axis-chart a new prop `clipPath [boolean]` that can implement a `<defs>` containing a rectangular clipPath with width and height of the chart display area. Thus if a line, area, or symbol extends outside the clipPath, it is not painted on the svg (use case is for scaling axes, changing domain or range).
Shape components all receive a `clipPathId [string]` prop that is used by the primitive component to access the clipPath.
=> add clipPath prop to axisChart

src/ui/choropleth-legend/src/choropleth-legend.jsx
Send a copy of the scale to the axis to ensure that the ticks are updated when the legend domain is updated
=> Fix choropleth legend scale

src/ui/shape/src/multi-line.jsx
...as per their propTypes declaration.
If object, spread directly as inline-style into Area or Line, respectively. If function, passed areaValues/lineValues and key as arguments. Result is spread as inline-style object into Area or Line, respectively.
=> multiline areaStyle and lineStyle props are either objects or functions

src/ui/choropleth/src/feature-layer.jsx, src/ui/choropleth/test/feature-layer.test.js
Providing a fix for choropleth feature layer. If value is zero, it does not default to `#ccc`, but Nil values do.
=> Feature layer colorscale

src/ui/select/src/select-option.css, src/ui/select/src/select-option.jsx, src/ui/select/src/test/select-option.test.js
- prevents calling props.selectValue on click
- prevents calling props.focusOption on mouseover
- prevents applying 'focused', 'selected' CSS classes
- tests included in commit
=> Allow disabling a SelectOption with option.disabled: true.

src/ui/select/src/select-option-label.jsx, src/ui/select/src/test/select-option-label.test.js
Currently, a `<Select />` option label will default to empty string if `option[labelKey]` is falsey. This makes it impossible to render a label with a '0', or 'false'. This fix changes behavior such that empty string will only be returned if `option[labelKey]` is undefined.
=> Select option labels should be able to be falsey

src/ui/shape/src/multi-scatter.jsx, src/ui/shape/src/scatter.jsx
A fix to #86. Setting defaultProps for scales removes warnings when AxisChart passes scales. Unfortunately, since scales is a required prop, a console warning won't show up if scales are not passed in other instances. If scales has a defaultProp, should scales be a required prop still?
=> Multiline scales

src/ui/index.js, src/ui/select/demo/app.jsx, src/ui/select/index.js, src/ui/select/src/multi-select.jsx, src/ui/select/src/select.jsx, src/ui/select/src/single-select.jsx
#89 A new component `Select` that merges a lot of common code from `MultiSelect` and `SingleSelect`. A multi-select component is created via props by the boolean prop `multiselect`. Any suggestions on renaming the prop are welcome. `Select` defaults to a single-select. The demo has been updated to include the new `Select` component.
=> Merge single multi select

src/ui/slider/src/slider.jsx
Truthiness test causes a bug when a range value is 0 (or potentially some other falsy value).
=> Check explicitly for undefined in Slider#updateValueFromEvent

src/ui/button/src/button.jsx
The objective of this PR is to close #76 -> Button: standardize className and style props.
I have tried to follow the newest conventions using combineStyles and combining the appropriate styles in propUpdates.  Disabled - seems to be the only auxiliary style to incorporate at this time (comparable to focus and the like that other components have).  
One point of style convention: I put the props to check in propUpdates into a `propsToCheck` variable.  This was something Aaron had pointed out as hard to read in my work on the Aster chart.
=> Ih 47 button class name style

README.md
Adding a link to our Travis badge, which displays at the top of the README (and thus on the project page), provides an easy way to navigate to the corresponding Travis project. This code was copied directly from Travis CI's status image creator.
=> Add link on travis badge

package-lock.json, package.json, webpack.demo.config.js
To remove the current warning: 
`We found potential security vulnerabilities in your dependencies.`
I have removed `webpack-notifier` as a dev-dependency. `webpack-notifier` will be re-installed when the npm version is updated with the current fix which is sitting on github.
https://github.com/Turbo87/webpack-notifier/pull/36
=> remove webpack-notifier until version update on npm

package.json, src/ui/tooltip/src/tooltip.jsx
This PR is a fix to a bug in firefox running on windows. It gets rid of render artifacts when the tooltip is set to `visibility:hidden`. According to [this article from 2012](https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/) translate has better performance. But maybe times have changed.
=> Tooltip fix

.travis.yml, package-lock.json, package.json
Travis has been failing. 
This PR replaces the `canvas-prebuilt` package with `canvas` since the former allows for the tests to pass as they should. However, since the `canvas-prebuilt` was, well, prebuilt,  the `.travis.yml` file needed to be updated. I used the node-canvas [.travis.yml](https://github.com/Automattic/node-canvas/blob/master/.travis.yml) as a template.
Other changes:
- Added `request` to package.json since test suite using node 10 fails tests without it.
- removed `dist` from `.travis.yml` [since trusty is now the default](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status).
=> Fix failing travis

.eslintrc.js, src/ui/shape/demo/app.jsx, src/ui/shape/demo/index.html, src/ui/shape/src/area.jsx, src/ui/shape/src/line.jsx, src/ui/shape/src/multi-line.jsx, src/ui/shape/test/area.test.js, src/ui/shape/test/line.test.js, src/ui/shape/test/multi-line.test.js, src/utils/animate.js, src/utils/index.js, src/utils/test/animate.test.js
This PR implements animation in the `<Line/>`, `<Area/>`, and `<MultiLine/>` components into the greater `react-move` animation effort branch of this repo. After this PR has been merged, I plan to make another PR to merge `react-move`  `=>`  `master`.
**Implementation details**
Animations are implemented using react-move's [`<Animate/>`](https://react-move.js.org/#/documentation/animate) wrapper since the `<Line/>` and `<Area/>` components essentially render a single `<path/>`. This differs from how `<Scatter />` was animated which uses react-move's [`<NodeGroup/>`](https://react-move.js.org/#/documentation/node-group) wrapper since it renders a _collection_ of `<Shape/>` components rather than a single component.
**Other PR notes**
- Existing unit testing scenarios have been extended to …
=> React move line

src/ui/select/src/select-option-label.jsx
The options don't bold as expected for non-hierarchical dropdowns because the styles are not being transferred to the DOM node.
=> Bug fix - Fix styles for non-hierarchical options

package-lock.json, package.json
While trying to polish up the `react-move` branch I found that Travis is failing...again. I have created a [ticket](https://jira.ihme.washington.edu/browse/STP-196) to eliminate the `canvas`/`canvas-prebuilt` dependency from the repo and mock it in the tests that utilize it. In the meantime, this patch seems to solve the problem.
=> Fix Travis for Node 10.3.0

package-lock.json, package.json
This PR trades the `codecov.io` package with `codecov` since github has given us a warning that the former has a vulnerable dependency of its own. Hopefully it's a painless update... so far so good!
=> Update vulnerable dependency.

package-lock.json, package.json
HME-UI's main exports are React components, so a user of the library must have a compatible version of React. React is also needed for development work, so it's a dev dependency too. react-dom is only used in demos, so it should be a dev dependency.
Information about `npm` peer dependencies: https://nodejs.org/en/blog/npm/peer-dependencies
=> Make react a peer dep and a dev dep; make react-dom a dev dep

package.json
This PR makes some revisions to the way we'll publish new versions on GitHub and npm. Now we can publish with a single command:
```bash
npm version <newversion>
```
where `<newversion>` will typically be `major`, `minor`, or `patch`
=> Revise npm publish

package-lock.json, package.json, src/ui/choropleth/src/choropleth.jsx, src/ui/choropleth/test/utils.js, src/utils/geo.js
As this issue (https://github.com/topojson/topojson/issues/304) on GitHub explains, `npm install` fails with an error if a project tries to include both `topojson` and `topojson-client`.  Because `topojson` is simply a light wrapper for the three subpackages `topojson-client`, `topojson-simplify`, and `topojson-server`, and IHME-UI only uses the first two of these, it seems simplest and most economical to replace the wrapper with the two constituent packages we're actually using.
=> Replace topojson package with topojson-client and topojson-simplify.

src/ui/shape/src/scatter.jsx
NodeGroup will only update when data changes, this means that it will not resize on window change until the data is also changing. To fix this issue I have made it so that we do not hit NodeGroup (renderAnimatedScatter) when the window is resized but will if the data is updated.
=> Fix animate Scatter resize issue

src/ui/compositions/bar-chart/src/bar-chart.jsx, src/utils/bar.js
This PR corrects an error in the implementation of the `BarChart` composition. According to the docs for that component, the prop `dataAccessors` should consist of "data accessors" (either string keys or functions), used for obtaining information about each datum object, but I discovered that the component only accepted strings for `dataAccessors`.
=> Bar chart data accessors

src/ui/axis-chart/demo/app.jsx, src/ui/axis/src/axis.jsx, src/ui/axis/src/orientedAxis.js, src/ui/axis/test/axis.test.js, src/ui/axis/test/utils.test.js, src/utils/axis.js, src/utils/strings.js
This PR resolves many of the bugs and fudge factors included in the **IH-75_auto-axis-formatting** merge. The only pieces that aren't calculated dynamically now are the **dx** & **dy** offsets for the tick labels and axis labels. After digging into the d3-axis code and many use cases, it seems that it is common practice to manipulate these offsets until the desired result is achieved. I experimented with various font sizes and text lengths and they all render the appropriate distance from the ticks. Please let me know if you have any suggestions.
=> Axis format hotfix

src/ui/slider/src/slider.jsx
Update range check to use isNil rather than previous buggy method (which errors on 0 being a part of the slider range).
=> Fix bug with slider so that 0 can be a part of the range

README.md, package.json, src/ui/axis/src/axis.jsx, src/ui/button/src/button.jsx, src/ui/choropleth/src/choropleth.jsx, src/ui/choropleth/src/controls.css, src/ui/choropleth/src/controls.jsx, src/ui/compositions/choropleth-legend/src/choropleth-legend.jsx, src/ui/compositions/choropleth-legend/src/slider-handle.jsx, src/ui/compositions/choropleth-legend/src/slider.jsx, src/ui/compositions/map/README.md, src/ui/compositions/map/demo/app.jsx, src/ui/compositions/map/src/map.jsx, src/ui/shape/src/scatter.jsx
This PR makes some accessibility and other improvements to the map zoom and legend controls.
-  I added a classname for the zoom controls button to the Map composition so that it could be passed to Choropleth and the Zoom Controls components. It looks like it was just skipped in the past.
- I changed the styles on the zoom controls to allow for the focus ring to be seen entirely and increased the size of the buttons so that a target area of 48px square (https://hub.ihme.washington.edu/display/DVT/Styling+checklist) was available. I also increased the the font size of the +, - and *. (Focus ring won't be visible in ihme-ui as it has no focus-visible styling enabled.)
- Following the basics of the design pattern for slider (https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/#slider), I …
=> FGH-681 map accessibility

src/ui/shape/src/scatter.jsx
Assigning directly to this.state is deprecated (except inside a components constructor) updated deprecated use in scatter.jsx to setState instead.
When using the Map component (which includes the legend, and thus the scatter component) there is a warning that has come up for a while involving the deprecated use of assigning this.state. This updates the last use of that in IHME-UI outside of a component constructor.
As seen in other deployments that use ihme-ui
`Warning: t.componentWillReceiveProps(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.`
As seen in the demo of map of ihme-ui itself
`react_devtools_backend.js:4026 Warning: Scatter.componentWillReceiveProps(): Assigning directly to this.state is deprecated (except …
=> Fix warning on Scatter component
